### ISSUE TITLE
Error message when using indicator_order function

### ISSUE THREAD

**Issue by stephshadwell** [ropensci/fingertipsR#73]
I am trying to pull the indicator order for the local health data, but i am getting the following error message when i execute the code below

```
lhorder_community <- indicator_order(DomainID = 1938133180, AreaTypeID = 3, ParentAreaTypeID = 102)
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html>  <html lang="en
                     (right here) ------^
```
i have checked versions, and i an using 0.2.4 (latest available on CRAN). I have also tried running for phof domains and get the same error

**Comment by sebastian-fox** [comment]
Thanks @stephshadwell - yes there's an issue with `indicator_order()`. This should be fixed in the dev version. I'll release 0.2.5 to CRAN in the next few days but to install the dev version you can do this:

```
devtools::install_github("rOpenSci/fingertipsR",
                         build_vignettes = TRUE,
                         dependencies = "suggests")
```

Could you let me know if this works and close the issue if so. Thank you :)

**Comment by MarkParker451** [comment]
I've just seen exactly the same error message when I use the nearest_neighbours function, is this linked to the same issue that's fixed in that dev version?
`our_neighbours <- nearest_neighbours(AreaCode = "E06000033")`

**Comment by sebastian-fox** [comment]
Hi @markparker451 - yes, it is the same issue but I've not yet fixed `nearest_neighbours()`. I'll get round to it today. I'll start a new issue for that so @stephshadwell can close this one if `indicator_order()` is fixed.

**Comment by stephshadwell** [comment]
thanks @sebastian-fox yes the dev version has fixed it :-)
